version: '2.1'

services:
  adguard:
    build: adguard
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf
    command:
      - "--no-check-update"
      - "--web-addr"
      - "0.0.0.0:84"
      - "--config"
      - "/opt/adguardhome/conf/AdGuardHome.yaml"
    ports:
      - 53:53/tcp #plain DNS
      - 53:53/udp #plain DNS
      - 67:67/udp #DHCP
      - 68:68/tcp #DHCP
      - 68:68/udp #DHCP
      - 84:84/tcp #Admin painel
      - 6060:6060/tcp #debugging profiles
  filebrowser:
    build: filebrowser
    restart: unless-stopped
    volumes:
      - media:/srv/cine
      - kavita-data:/srv/biblioteca
      - httpd:/srv/portal
    ports:
      - 85:80
    command: -- c
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 86:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - "jellyfin-config:/config"
      - "jellyfin-cache:/cache"
      - "media:/media"
      - "jellyfin-lib:/opt/vc/lib"
    environment:
      PUID: "1000"
      PGID: "1000"
  hostname:
    image: balenablocks/hostname:latest
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: waiapi
  kavita:
    build: kavita
    container_name: kavita
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Belem
    volumes:
      - kavita-config:/config
      - kavita-data:/books
    ports:
      - 81:5000
    restart: unless-stopped
  sync:
    build: sync
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
    volumes:
      - sync-config:/config
      - media:/data/media
      - kavita-data:/data/library
    ports:
      - 82:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  ntp:
    image: cturra/ntp:latest
    restart: always
    ports:
      - 123:123/udp
    # read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
  httpd:
    build: httpd
    ports:
      - 80:80
    volumes:
      - httpd:/usr/local/apache2/htdocs
    restart: unless-stopped
  # kolibri:
  #   network_mode: host
  #   build: kolibri
  #   volumes:
  #     - kolibri:/root/.kolibri
  #     - pulse:/run/pulse
  # # https://github.com/wg-easy/wg-easy
  # wireguard:
  #   image: weejewel/wg-easy
  #   environment:
  #     - WG_HOST=192.168.0.1
  #     - PASSWORD=admin123
  #   volumes:
  #     - wireguard:/etc/wireguard
  #   ports:
  #     - "51820:51820/udp"
  #     - "83:51821/tcp"
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv4.ip_forward=1
  #   restart: unless-stopped
  #   privileged: true
  #   labels:
  #     io.balena.features.kernel-modules: "1"
  #     io.balena.features.dbus: "1"
volumes:
  adguard-conf:
  adguard-work:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  sync-config:
  kavita-config:
  kavita-data:
  httpd:
  # kolibri:
  # pulse:
  # wireguard:
