version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  sync-config:
  sync-downloads:
  web-portal:
services:
  # httpd
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: pihole
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
  # https://github.com/klutchell/unbound-dnscrypt
  unbound:
    build:
      context: unbound
    privileged: true
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname:latest
    restart: 'no'
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: guarani
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    restart: unless-stopped
    ports:
      - 80:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - 'jellyfin-config:/config'
      - 'jellyfin-cache:/cache'
      - 'media:/media'
      - 'jellyfin-lib:/opt/vc/lib'
    environment:
      PUID: '1000'
      PGID: '1000'
  sync:
    image: lscr.io/linuxserver/syncthing
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
    volumes:
      - 'sync-config:/config'
      - 'media:/data'
    ports:
      - 82:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
