version: "2.1"

volumes:
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:

services:
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    build: pihole
    privileged: true
    volumes:
      - "pihole_config:/etc/pihole"
      - "dnsmasq_config:/etc/dnsmasq.d"
    dns:
      - "127.0.0.1"
      - "1.1.1.1"
    network_mode: host
    labels:
      io.balena.features.dbus: "1"

  # https://hub.docker.com/r/klutchell/dnscrypt-proxy
  dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy
    privileged: true
    expose:
      - "5300/udp"
      - "5300/tcp"
    volumes:
      - "dnscrypt_config:/config"
    dns:
      - 1.1.1.1
    restart: unless-stopped

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname:latest
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: pihole
