version: '2.1'

services:
  adguard:
    build: adguard
    network_mode: host
    privileged: true
    volumes:
      - 'adguard_work:/opt/adguardhome/work:rw'
      - 'adguard_conf:/opt/adguardhome/conf:rw'
    command:
      - "--no-check-update"
      - "--web-addr"
      - "0.0.0.0:84"
      - "--config"
      - "/opt/adguardhome/conf/AdGuardHome.yaml"
  # https://github.com/wg-easy/wg-easy
  wg-easy:
    image: weejewel/wg-easy
    environment:
      - WG_HOST=192.168.0.1
      - PASSWORD=admin
    volumes:
      - wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "83:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    privileged: true
    labels:
      io.balena.features.kernel-modules: "1"
      io.balena.features.dbus: "1"
  hostname:
    image: balenablocks/hostname:latest
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: waiapi
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 80:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - "jellyfin-config:/config"
      - "jellyfin-cache:/cache"
      - "media:/media"
      - "jellyfin-lib:/opt/vc/lib"
    environment:
      PUID: "1000"
      PGID: "1000"
  sync:
    build: sync
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
    volumes:
      - "sync-config:/config"
      - "media:/data"
    ports:
      - 82:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  ntp:
    image: cturra/ntp:latest
    restart: always
    ports:
      - 123:123/udp
    # read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
volumes:
  adguard_conf:
  adguard_work:
  wireguard:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  sync-config:
