version: '2.1'

services:
  pihole:
    build: pihole
    volumes:
      - pihole_etc:/etc/pihole
      - pihole_dnsmasq:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    environment:
      LOCAL_IP: '10.75.0.113'
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '84:80/tcp'
      - '443:443/tcp'
  adguard:
    image: adguard/adguardhome:latest
    volumes:
      - adguard_conf:/opt/adguardhome/conf
      - adguard_work:/opt/adguardhome/work
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '85:80/tcp'
      - '443:443/tcp'
  wireguard:
    image: linuxserver/wireguard:latest
    volumes:
      - wireguard_config:/config
      - wireguard_lib:/lib/modules
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - '51820:51820/udp'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - SERVERURL=wireguard.example.com
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    restart: unless-stopped
  keexybox:
    image: keexybox/keexybox:latest
    volumes:
      - keexybox_config:/config
      - keexybox_data:/data
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    ports:
      - '86:80'
      - '3128:3128'
  hostname:
    image: balenablocks/hostname:latest
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: waiapi
  jellyfin:
    image: jellyfin/jellyfin
    restart: unless-stopped
    ports:
      - 80:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - "jellyfin-config:/config"
      - "jellyfin-cache:/cache"
      - "media:/media"
      - "jellyfin-lib:/opt/vc/lib"
    environment:
      PUID: "1000"
      PGID: "1000"
  sync:
    build: sync
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
    volumes:
      - "sync-config:/config"
      - "media:/data"
    ports:
      - 82:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  ntp:
    image: cturra/ntp:latest
    restart: always
    ports:
      - 123:123/udp
    # read_only: true
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
volumes:
  pihole_etc:
  pihole_dnsmasq:
  adguard_conf:
  adguard_work:
  wireguard_config:
  wireguard_lib:
  keexybox_config:
  keexybox_data:
  jellyfin-config:
  jellyfin-cache:
  media:
  jellyfin-lib:
  sync-config:
