name: Balena Push Preload Main
on:
  push:
    branches:
      - main
jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Balena image
        uses: ./.github/actions/deploy-balena-image
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          balena_fleet: ${{ secrets.BALENA_FLEET }}
          github_ref: ${{ github.ref }}
          github_head_ref: ${{ github.head_ref }}
          balena_release_type: draft
          release_tag: main
          commit: ${{ github.sha }}

  balena-build-images:
    # strategy:
    #   matrix:
    #     board: ['pi3', 'pi4']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get base board
        # run: |
        #   if [ "${{ matrix.board }}" == 'pi3' ]; then
        #     echo "BALENA_IMAGE=raspberrypi3" >> $GITHUB_ENV
        #   elif [ "${{ matrix.board }}" == 'pi4' ]; then
        #     echo "BALENA_IMAGE=raspberrypi4-64" >> $GITHUB_ENV
        #   fi
        run: |
          echo "BALENA_IMAGE=raspberrypi4-64" >> $GITHUB_ENV
      - name: balena CLI Action - download
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os download "$BALENA_IMAGE" \
              --output "$BALENA_IMAGE.img" \
              --version default
          balena_cli_version: 17.2.2

      - name: balena CLI Action - preload
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            preload \
              "$BALENA_IMAGE.img" \
              --fleet ${{secrets.BALENA_FLEET}} \
              --dont-check-arch  \
              --commit latest
          balena_cli_version: 17.2.2

      - name: balena CLI Action - configure
        uses: balena-labs-research/community-cli-action@1.0.0
        with:
          balena_token: ${{secrets.BALENA_TOKEN}}
          balena_cli_commands: |
            os configure \
              "$BALENA_IMAGE.img" \
              --config-network=ethernet  \
              --fleet ${{secrets.BALENA_FLEET}}
          balena_cli_version: 17.2.2

      - name: Zip image
        run: |
          zip -9 \
            "$(date -I)-$BALENA_IMAGE.zip" \
            "$BALENA_IMAGE.img"
      - uses: actions/upload-artifact@v3
        with:
          name: Release file
          path: "*.zip"