name: Balena Push Preload Main
on:
  push:
    branches:
      - main
jobs:
  balena-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Balena image
        uses: ./.github/actions/deploy-balena-image
        with:
          balena_token: ${{ secrets.BALENA_TOKEN }}
          balena_fleet: ${{ secrets.BALENA_FLEET }}
          github_ref: ${{ github.ref }}
          github_head_ref: ${{ github.head_ref }}
          balena_release_type: draft
          release_tag: main
          commit: ${{ github.sha }}
